version: "3.8"
services:
#  truffle:
#    image: trufflesuite/ganache-cli:latest
#    ports:
#      - 8545:8545
  arango:
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: 'arangodb'
    ports:
      - 8529:8529
  analyzer:
    build: .
    ports:
      - 5000:5000
    environment:
      APP_PATH: /var/app
      GIT_ROOT: /var/app/repos
      ARANGO_URL: http://arango:8529
      ARANGO_DB: analyzer
      ARANGO_USER: root
      ARANGO_PASS: arangodb
    depends_on:
      - arango
#      - truffle
    volumes:
      - .:/var/app
  viewer:
    build: ./vue
    ports:
      - 8080:8080
    depends_on:
      - analyzer
    volumes:
      - ./vue:/var/app
#  solc:
#    image: ethereum/solc:stable
#    command: "-o /sources/output "
#    volumes:
#      - ./solidity:/sources
